---
abstract: 'Lego part image objects.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0.22
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.05
  Lego::Part: 0.01
  Test::MockObject: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lego-Part-Image
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Class::Utils: 0.03
  Error::Pure: 0.22
  Readonly: 0
  Scalar::Util: 0
  perl: "\x05\x06\0"
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Lego-Part-Image
  homepage: https://github.com/tupinek/Lego-Part-Image
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Lego-Part-Image
version: '0.03'
